### ISSUE TITLE
[Dificuldade] Não consegui importar banca de Prof. Substituto

### ISSUE THREAD

**Issue by ricardofranco3** [inf-ufg-br/radoc-2022#10]
Olá comissão, não consegui importar a banca de concurso para prof. substituto que participei no INF no início de 2022. Já realizei o cadastro dela no Lattes inserindo o ano de 2022, conforme informado. Mas, mesmo assim, não consegui importá-la via SIGAA para o SICAD+.

Segui os passos abaixo (descrito em https://cercomp.ufg.br/p/mapeamento-sicad):
- Produção ter sido cadastrada no Lattes - menu "Participação em bancas de comissões julgadoras" (**ok**)
- Produção ter sido importada no Produção intelectual (**a produção não apareceu **)
- Produção ter o ano igual ao ano base (** inseri 2022 no lattes**)
- Produção ser complementada: campo "Categoria" ("Professor Substituto") (**não consegui inserir porque não apareceu no SIGAA**)

Mesmo assim, não consigo visualizar a banca no SIGAA:
SIGAA > Portal do Docente > Produção intelectual > Minhas produções - Lattes > Participação em Banca > Membro de banca de concurso para docente efetivo

Obrigado pela atenção

**Comment by MarciaCappelle** [comment]
Ricardo, quando foi realizado o lançamento? A importação da produção do Lattes pelo SIGAA não é instantânea. Pode demorar um ou dois dias.

**Comment by ricardofranco3** [comment]
Oi Marcia, o lançamento foi realizado junto com os artigos que eu havia publicado em 2022. Os artigos e demais itens que eu inclui (IC, banca de doutorado), foram inseridos no RADOC, somente a banca de prof. substituto não aparece no SICAD+, nem no SIGAA > Membro de banca de concurso para docente efetivo (aparece a mensagem "Nenhuma participação como membro de banca de concurso para docente efetivo encontrada.").
Eu arriscaria dizer que no SIGAA, em **SIGAA > Portal do Docente > Produção intelectual > Minhas produções - Lattes > Participação em Banca > Membro de banca de concurso para docente efetivo** só aparece as bancas para prof. efetivos e não os de prof. substituto.

**Comment by MarciaCappelle** [comment]
Ricardo, pelo o que eu pude observar, esse item "Membro de banca de concurso para docente substituto" não está aparecendo para ser lançado manualmente no SIGAA e nem está sendo importado do Lattes. Sugiro abrir uma chamada no Cercomp relatando o caso.
