### ISSUE TITLE
Bolsista de produtividade no CNPq

### ISSUE THREAD

**Issue by martinswellington** [inf-ufg-br/radoc-2022#16]
Olá pessoal, notei que a informação "Bolsista de Produtividade em Pesquisa do CNPq - Nível 2", que está no meu Lattes (http://lattes.cnpq.br/3041686206689904) não aparece no relatório gerado pelo SICAD+. Acho que esta informação é importada de algum banco do CNPq, pois não me lembro de a ter inserido no Lattes.

**Comment by plinioleitao** [comment]
Favor ver Item 20 da Tabela II-1, no link abaixo
https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/painel-radoc-producao.md/
