### ISSUE TITLE
[Dificuldade] Como inserir orientação de monitoria no Radoc?

### ISSUE THREAD

**Issue by thiersonufg** [inf-ufg-br/radoc-2022#3]
Não estou sabendo como inserir informações sobre orientações de monitor no SIGAA.

**Comment by plinioleitao** [comment]
Oi Thierson,
A <ins>orientação de monitoria</ins> ocorre via importação a partir do software **SIGAA>Monitoria**.
Contudo, conforme posto em [Fontes das informações do SICAD+](https://cercomp.ufg.br/p/mapeamento-sicad), a Atividade **V-1.27** (Aluno orientado em programa de monitoria) está em manutenção, a saber: "Ajuste em andamento no Módulo Monitoria e critérios para importação". 
Vamos aguardar um pouco para que essa importação se torne funcional.

**Comment by thiersonufg** [comment]
Muito obrigado Plínio. Então por enquanto fica essa pendência no SICAD
