### ISSUE TITLE
[Dificuldade] O que fazer com orientações em que o aluno abandonou o mestrado?

### ISSUE THREAD

**Issue by thiersonufg** [inf-ufg-br/radoc-2022#4]
Há uma orientação de aluno de mestrado aberta. Está contando como uma orientação em andamento, mas o aluno não concluiu e foi inclusive excluído do programa. Essa orientação contou corretamente como pontuação para mim até o ano de 2021, mas o aluno abandonou o mestrado, não se matriculando no primeiro semestre de 2022. Eu marquei a opção "Discente desligado", mas não sei se é suficiente. Além disso, ao marcar o discente com desligado e clicar em Alterar, a condição dessa produção continua como "produção não complementada".

**Comment by plinioleitao** [comment]
Olá Thierson,

Por favor, veja algumas instruções:
- Alimentar o _Lattes_ para indicar que a orientação foi interrompida/concluída.
- Complementar o registro importado do _Lattes_ (instruções [AQUI](https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/fonte-lattes.md)), visando a indicar que o discente foi desligado e a data de término.

Foram apresentados casos em que orientações concluídas/interrompidas em anos anteriores ainda estão presentes no RADOC 2022 com _status_ "em andamento". A Comissão enviou mensagem sobre tal para o e-mail sicad@ufg.br, cuja resposta foi que esses casos estão na pauta da equipe responsável pelo SICAD+.

Grato, Comissão RADOC 2022.

**Comment by rsalvini** [comment]
Todos os alunos que concluíram normalmente o mestrado, ou seja, que fizeram a defesa da dissertação, eu devo alterar no SIGAA o campo "Discente Desligado" para "Sim"?

**Comment by thiersonufg** [comment]
> Olá Thierson,
> 
> Por favor, veja algumas instruções:
> 
> * Alimentar o _Lattes_ para indicar que a orientação foi interrompida/concluída.
> * Complementar o registro importado do _Lattes_ (instruções [AQUI](https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/fonte-lattes.md)), visando a indicar que o discente foi desligado e a data de término.
> 
> Foram apresentados casos em que orientações concluídas/interrompidas em anos anteriores ainda estão presentes no RADOC 2022 com _status_ "em andamento". A Comissão enviou mensagem sobre tal para o e-mail [sicad@ufg.br](mailto:sicad@ufg.br), cuja resposta foi que esses casos estão na pauta da equipe responsável pelo SICAD+.
> 
> Grato, Comissão RADOC 2022.

Mas Plínio, acho que há uma impasse nesse caso, porque não existe a opção no lates de orientação "interrompida" e sim "concluída", mas se eu coloco essa opção, o Lates considera que foi uma tese defendida e aprovada, o que não é o caso. Talvez o correto seria excluir essa orientação do Lattes?

**Comment by plinioleitao** [comment]
Sobre o comentário do @rsalvini , consultei o prof. Maurício Donizetti (Pro Pessoas), cuja resposta foi: não precisa marcar o discente como desligado , mas a orientação deve estar concluída no _Lattes_.

Sobre o comentário do @thiersonufg , penso que a exclusão do _Lattes_ pode ser uma solução para o caso, contudo vale lembrar que há problemas de sincronização com o _Lattes_ (não é garantido que o registro será excluído do RADOC: se fizer o teste, por favor deixe-me saber o resultado).

Grato, Comissão RADOC 2022.
