### ISSUE TITLE
[Dificuldade] Como inserir atividades de qualificação?

### ISSUE THREAD

**Issue by adailtonaraujo** [inf-ufg-br/radoc-2022#5]
No RADOC  antigo tinha uma área onde eu cadastrava as **atividades de qualificação**, não encontrei onde incluir/pontuar essas informações nesse novo sistema ou em um sistema integrador que vai trazer esses dados. Teria 2 itens para cadastrar nessa área (conforme me foi orientado no ano passado).

Item 1: **Docente regularmente matriculado em curso de doutorado com relatórios de pós-graduação aprovados** (estou cursando doutorado)
Item 2: **Participação em Congressos, Seminários, Encontros, Jornadas etc.** (um evento que participei)

**Comment by plinioleitao** [comment]
Olá Adailton,

Em ambos os casos, favor seguir o Fluxo para [Registros RADOC inseridos de forma MANUAL](https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/fonte-manual.md).

Para maior detalhes:
- Sobre Item 1, Docente regularmente matriculado em curso de doutorado com relatórios de pós-graduação aprovados:
  - Favor ver a orientação na Tabela [V–3) ATIVIDADES DE APRENDIZADO E APERFEIÇOAMENTO](https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/painel-radoc-outras.md#radoc-outras-atividades).
- Sobre Item 2, Participação em Congressos, Seminários, Encontros, Jornadas etc.:
  - Favor ver a orientação na Tabela [V–3) ATIVIDADES DE APRENDIZADO E APERFEIÇOAMENTO](https://github.com/inf-ufg-br/radoc-2022/blob/main/doc/painel-radoc-outras.md#radoc-outras-atividades).

Grato, Comissão RADOC 2022.
