### ISSUE TITLE
[Dificuldade] < Monitoria, Projeto de Ensino, Planejamento Pedagógico >

### ISSUE THREAD

**Issue by cristianebrf** [inf-ufg-br/radoc-2022#9]
1) Tenho 2 alunos de monitoria que iniciaram suas atividades em nesse último processo de monitoria relacionado com um projeto de ensino. Eles não aparecem para mim no Sicad+, assim como os orientandos com monitoria já finalizada aparecem (de processos anteriores). O que fazer? 

2) Sobre projeto de ensino -> aparece no Sigaa, contempla os requisitos exigidos e não aparece no Sicad+ (Projeto: Ensino de algoritmos, estruturas de dados e programação 2022)

3) É preciso lançarmos as horas de planejamento pedagógico ou isso vem automático feito pela secretaria? Tenho 5 horas do planejamento pedagógico e administrativo do 1º semestre letivo de 2022

**Comment by cristianebrf** [comment]
Olá, Comissão.
Sobre o item 2) Projeto de Ensino, o mesmo já está aparecendo no Sicad+ agora! Favor desconsiderar a dúvida número 2).

**Comment by plinioleitao** [comment]
Olá Cristiane,

**Sobre o Item 1) "Tenho 2 alunos de monitoria que iniciaram ..."**:
Favor ver a resposta da [ISSUE #3](https://github.com/inf-ufg-br/radoc-2022/issues/3).

**Sobre o Item 3) "É preciso lançarmos as horas de planejamento ..."**:
As atividades mencionadas neste item serão formalizadas via portarias, as quais serão emitidas próximas ao final do ano. O conteúdo das portarias serão automaticamente importados para o RADOC, visto que as mesmas serão emitidas via SIGRH-Portarias.

Grato, Comissão RADOC 2022.
